version: '3.8'

services:
  toll-automation:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - ENV=production
    restart: unless-stopped